version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bash -c "rm -rf public/packs; bin/webpack-dev-server"
    volumes:
      - .:/myapp
    ports:
      - "3035:3035"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - mailcatcher
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
      - webpacker
volumes:
  postgres_data_container:
